name: Continuous Integration

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  
  ## Runs Nx build, lint, and test targets for projects affected by head branch
  extract-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: get the sha
      run: |
        echo "$GITHUB_CONTEXT"| jq '.event.commits[].id' | tail -2 | head -1 |sed 's/\"//g'
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: Download coverage artifact
      uses: actions/download-artifact@v3
      with:
        name: code-coverage-report-${{github.event.before}}
    - name: Run consoomer
      run: node coverage-consoomer.js coverage/test/coverage-summary.json